# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

platform :ios, '7.0'

inhibit_all_warnings!

pod 'AFNetworking', '2.5.4'
pod 'JGProgressHUD', '1.3'
pod 'ObjectiveRecord', '1.5.0'
pod 'BlocksKit', '2.2.5'
pod 'WYPopoverController', '0.3.8'
pod 'INTULocationManager' , '3.0.3'
pod 'MBProgressHUD', '0.9.1'
pod 'TOWebViewController', '2.0.19'